[project]
name = "pycomputer"
version = "0.1.1"
description = "A text-based and TUI computer made in Python."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pycomputersdk",
    "requests>=2.34.2",
    "tuiro>=0.1.1",
]

[build-system]
requires = ["hatchling>=1.31.0"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel.force-include]
"README.md" = "README.md"
"LICENSE" = "LICENSE"

[tool.uv.sources]
pycomputersdk = { workspace = true }
