[project]
name = "pycomputersdk"
version = "0.1.0"
description = "SDK for developing pyComputer apps"
authors = [
    { name = "NellowTCS", email = "neeljaiswal23@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "pytest>=8.0",
    "requests>=2.34.2",
    "tuiro>=0.1.1",
]
optional-dependencies = { dev = ["pytest>=8.0"] }

[project.scripts]
pycomp = "pycomputersdk.cli.main:main"

[build-system]
requires = ["hatchling>=1.27.0"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist.force-include]
"../pyComputer/pycomputer" = "pycomputer"

[tool.hatch.build.targets.wheel]
packages = ["src/pycomputersdk"]

[tool.hatch.build.targets.wheel.force-include]
"pycomputer" = "pycomputer"

[tool.uv.sources]
pycomputer = { workspace = true }
